name: Review PR with OpenAI GPT model
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  run-local-action:
    steps:
    - name: Run checkout
      uses: actions/checkout@v2
    - name: Run custom action
      uses: ./.github/actions/action