name: Review PR with OpenAI GPT model
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  run-local-action:
    runs-on: ubuntu-latest
    steps:
    - name: Run checkout
      uses: actions/checkout@v2
    - name: Display working directory files
      run: |
        echo "Working directory files:"
        ls -al
    - name: Run custom action
      uses: ./.github/actions/action